# Groep Web
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-edit-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: Group
  namespace: web
  name: e7751e4a-7b7c-412a-bf18-18f3294574aa
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-view-access
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: Group
  namespace: api
  name: e7751e4a-7b7c-412a-bf18-18f3294574aa
---
# Groep Api
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-edit-access
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: Group
  namespace: api
  name: 34a8a5d3-dd06-48a0-9146-26e8fdb48f10
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-view-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: Group
  namespace: web
  name: 34a8a5d3-dd06-48a0-9146-26e8fdb48f10