apiVersion: v1
kind: Namespace
metadata:
  name: web
---
apiVersion: v1
kind: Namespace
metadata:
  name: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: poi
        image: registryavj6801.azurecr.io/tripinsights/poi:1.0
        env:
        - name: SQL_USER 
          valueFrom:
            secretKeyRef:
              name: tripsecret
              key: SQL_USER_SECRET
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tripsecret
              key: SQL_PASSWORD_SECRET
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: tripsecret
              key: SQL_SERVER_SECRET
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: tripsecret
              key: SQL_DBNAME_SECRET
        ports:
        - containerPort: 80
          name: webport
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: api
spec:
  ports:
  - port: 80
  selector:
    app: poi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userjava
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userjava
  template:
    metadata:
      labels:
        app: userjava
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: userjava
        image: registryavj6801.azurecr.io/tripinsights/userapi:1.0
        env:
        - name: SQL_USER 
          valueFrom:
            secretKeyRef:
              name: tripsecret
              key: SQL_USER_SECRET
        - name: SQL_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: tripsecret
              key: SQL_PASSWORD_SECRET
        - name: SQL_SERVER 
          valueFrom:
            secretKeyRef:
              name: tripsecret
              key: SQL_SERVER_SECRET
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: tripsecret
              key: SQL_DBNAME_SECRET    
        ports:
        - containerPort: 80
          name: webport
---
apiVersion: v1
kind: Service
metadata:
  name: userjava
  namespace: api
spec:
  ports:
  - port: 80
  selector:
    app: userjava
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: userprofile
        image: registryavj6801.azurecr.io/tripinsights/userprofile:1.0
        env:
        - name: SQL_USER 
          valueFrom:
            secretKeyRef:
              name: tripsecret
              key: SQL_USER_SECRET
        - name: SQL_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: tripsecret
              key: SQL_PASSWORD_SECRET
        - name: SQL_SERVER 
          valueFrom:
            secretKeyRef:
              name: tripsecret
              key: SQL_SERVER_SECRET
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: tripsecret
              key: SQL_DBNAME_SECRET    
        ports:
        - containerPort: 80
          name: webport
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: api
spec:
  ports:
  - port: 80
  selector:
    app: userprofile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: trips
        image: registryavj6801.azurecr.io/tripinsights/trips:1.0
        env:
        - name: SQL_USER 
          valueFrom:
            secretKeyRef:
              name: tripsecret
              key: SQL_USER_SECRET
        - name: SQL_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: tripsecret
              key: SQL_PASSWORD_SECRET
        - name: SQL_SERVER 
          valueFrom:
            secretKeyRef:
              name: tripsecret
              key: SQL_SERVER_SECRET
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: tripsecret
              key: SQL_DBNAME_SECRET        
        ports:
        - containerPort: 80
          name: webport
---
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: api
spec:
  ports:
  - port: 80
  selector:
    app: trips
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: tripviewer
        image: registryavj6801.azurecr.io/tripinsights/tripviewer:1.0
        env:
        - name: ASPNETCORE_ENVIRONMENT 
          value: Development
        - name: TRIPS_API_ENDPOINT 
          value: "http://trips.api"
        - name: USERPROFILE_API_ENDPOINT 
          value: "http://userprofile.api"
        ports:
        - containerPort: 80
          name: webport
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: web
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: tripviewer