apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: poi
        image: registryavj6801.azurecr.io/tripinsights/poi:1.0
        env:
        - name: SQL_USER 
          value: "sqladminaVj6801"
        - name: SQL_PASSWORD 
          value: "test123!@"
        - name: SQL_SERVER 
          value: "sqlserveravj6801.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        ports:
        - containerPort: 80
          name: webport
---
apiVersion: v1
kind: Service
metadata:
  name: poi
spec:
  ports:
  - port: 80
  selector:
    app: poi