apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: tripviewer
        image: registryavj6801.azurecr.io/tripinsights/tripviewer:1.0
        env:
        - name: TRIPS_API_ENDPOINT 
          value: "http://trips"
        - name: USERPROFILE_API_ENDPOINT 
          value: "http://userprofile"
        ports:
        - containerPort: 80
          name: webport
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: tripviewer