apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: userprofile
        image: registryavj6801.azurecr.io/tripinsights/userprofile:1.0
        env:
        - name: SQL_USER 
          value: "sqladminaVj6801"
        - name: SQL_PASSWORD 
          value: "test123!@"
        - name: SQL_SERVER 
          value: "sqlserveravj6801.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        ports:
        - containerPort: 80
          name: webport
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
spec:
  ports:
  - port: 80
  selector:
    app: userprofile